{
 "title": "Dashboard Banco de Dados DevOps",
 "tags": [
  "Banco de Dados",
  "DevOps"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus Node Status",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "Node {{instance}}" }
   ]
  },
  {
   "title": "Conexões ativas do MariaDB",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Conexões ativas"
    }
   ]
  },
  {
   "title": "Uso de CPU do Prometheus",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Uso de Memória do Prometheus",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes[1m])",
     "legendFormat": "Uso de Memória"
    }
   ]
  },
  {
   "title": "Tempo de Resposta do MariaDB",
   "type": "graph",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_seconds_since_slow_log[1m])",
     "legendFormat": "Tempo de Resposta (segundos)"
    }
   ]
  }
 ]
}